# Security Code Scan (SCS) Config
# See: https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Config/Main.yml

Version: 3.0

# Set to 'true' to get fake SCS0000 warning when analysis completes.
ReportAnalysisCompletion: true

# Set to 'true' to see more warnings
AuditMode: false
